Patch 1
MikeWang000000/Natter pull request #99
Opened 2024-06-17 12:07 UTC by MasterOfStar

尝试修复了cf-srv.py

2024-06-17 12:25 UTC, liuran001 commented
find srv 那边的参数还是不对
手机上网页版 GitHub 太难用了，你照我这个再改一下吧（

https://github.com/liuran001/Natter/commit/00cff37e4f138a4cba91c43a869398b33aea13cb

2024-06-26 19:16 UTC, MikeWang000000 commented
十分感谢！稍后我会合入

2025-10-08 16:08 UTC, MikeWang000000 requested changes

2025-10-08 16:08 UTC, MikeWang000000 commented on natter-docker/minecraft/cf-srv.py
> +            if rec_data["type"] == "SRV" and rec_data["name"] == f"{service}{protocol}.{name}":
这里应当是 `f"{service}.{protocol}.{name}"`，少了一个点。
```suggestion
            if rec_data["type"] == "SRV" and rec_data["name"] == f"{service}.{protocol}.{name}":
```

2025-10-08 16:11 UTC, MikeWang000000 requested changes

2025-10-08 16:11 UTC, MikeWang000000 commented on natter-docker/minecraft/cf-srv.py
> +                "name":     f"{service}{protocol}.{name}",
同样，这里也少了一个点。
```suggestion
                "name":     f"{service}.{protocol}.{name}",
```

2025-10-08 16:16 UTC, merged

2025-10-08 16:24 UTC, MikeWang000000 commented
感谢你们的贡献！
@MasterOfStar @liuran001